server:
  port: 8888
  
spring:
  # Spring  cloud:
    config:
      server:
        git:
          uri: https://github.com/fullyavenged/config-files
          default-label: main
          search-paths:          - '*service'